const fs = require('fs');
const path = require('path');

const newInternships = [
    { id: 139, org: "IBM", title: "IBM Extreme Blue Internship", domain: "Cloud & AI", desc: "Premium summer internship focusing on business and technical innovation in Cloud and AI.", duration: "12 weeks", stipend: "Paid", tags: ["ibm", "cloud", "ai", "summer"], location: "Bangalore", workType: "Hybrid", role: "Software Developer", url: "https://www.ibm.com/careers/internships" },
    { id: 140, org: "Intel", title: "Intel Hardware Engineering Intern", domain: "Electronics", desc: "Work on next-generation processors and hardware validation.", duration: "6 months", stipend: "Paid", tags: ["intel", "hardware", "electronics", "engineering"], location: "Bangalore", workType: "In Office", role: "Hardware Engineer", url: "https://jobs.intel.com/internships" },
    { id: 141, org: "Cisco", title: "Cisco Software Engineer Intern", domain: "Networking", desc: "Develop networking solutions and software-defined infrastructure.", duration: "6 months", stipend: "Paid", tags: ["cisco", "networking", "sde"], location: "Pune", workType: "Hybrid", role: "Software Engineer", url: "https://jobs.cisco.com/jobs/SearchJobs/?listFilterMode=1&projectOffset=0&keyword=intern" },
    { id: 142, org: "Oracle", title: "Oracle Cloud Infrastructure Intern", domain: "Cloud Computing", desc: "Build scalable cloud infrastructure and core services for Oracle Cloud.", duration: "3 months", stipend: "Paid", tags: ["oracle", "cloud", "infrastructure"], location: "Hyderabad", workType: "In Office", role: "Cloud Engineer", url: "https://www.oracle.com/careers/students/" },
    { id: 143, org: "SAP", title: "SAP Labs Developer Intern", domain: "Enterprise Software", desc: "Contribute to enterprise software solutions and cloud-native development.", duration: "6 months", stipend: "Paid", tags: ["sap", "enterprise", "development"], location: "Bangalore", workType: "Hybrid", role: "Developer", url: "https://jobs.sap.com/go/SAP-Students-and-Graduates/3494701/" },
    { id: 144, org: "VMware", title: "VMware R&D Virtualization Intern", domain: "Cloud & Virtualization", desc: "Work on core virtualization technologies and cloud management products.", duration: "3 months", stipend: "Paid", tags: ["vmware", "cloud", "virtualization"], location: "Remote", workType: "Work from Home", role: "R&D Engineer", url: "https://careers.vmware.com/students" },
    { id: 145, org: "Intuit", title: "Intuit FinTech SDE Intern", domain: "FinTech", desc: "Develop financial software products for millions of consumers and small businesses.", duration: "6 months", stipend: "Paid", tags: ["intuit", "fintech", "sde"], location: "Bangalore", workType: "Hybrid", role: "Software Engineer", url: "https://jobs.intuit.com/students" },
    { id: 146, org: "Paytm", title: "Paytm Backend Developer Intern", domain: "FinTech", desc: "Build highly scalable payment gateways and financial services.", duration: "3 months", stipend: "₹35,000/mo", tags: ["paytm", "fintech", "backend"], location: "Noida", workType: "In Office", role: "Backend Developer", url: "https://careers.paytm.com/" },
    { id: 147, org: "MakeMyTrip", title: "MakeMyTrip Frontend Intern", domain: "Web Development", desc: "Create seamless travel booking experiences using React.js and Next.js.", duration: "3 months", stipend: "₹30,000/mo", tags: ["makemytrip", "frontend", "web"], location: "Gurgaon", workType: "Hybrid", role: "Frontend Developer", url: "https://careers.makemytrip.com/" },
    { id: 148, org: "Dream11", title: "Dream11 Data Engineering Intern", domain: "Data Science", desc: "Build resilient data pipelines for real-time sports fantasy analytics.", duration: "3 months", stipend: "₹40,000/mo", tags: ["dream11", "data", "engineering"], location: "Mumbai", workType: "In Office", role: "Data Engineer", url: "https://about.dream11.in/careers" },
    { id: 149, org: "Myntra", title: "Myntra App Development Intern", domain: "Mobile Development", desc: "Develop features for India's leading fashion e-commerce mobile app.", duration: "6 months", stipend: "₹45,000/mo", tags: ["myntra", "app", "mobile", "android"], location: "Bangalore", workType: "Hybrid", role: "Android Developer", url: "https://careers.myntra.com/" },
    { id: 150, org: "Lenskart", title: "Lenskart Computer Vision Intern", domain: "AI/ML", desc: "Develop 3D try-on and facial analysis features using computer vision.", duration: "3 months", stipend: "₹30,000/mo", tags: ["lenskart", "cv", "ai", "ml"], location: "Gurgaon", workType: "In Office", role: "CV Engineer", url: "https://hiring.lenskart.com/" },
    { id: 151, org: "Oyo", title: "Oyo Revenue Management Intern", domain: "Finance", desc: "Analyze pricing strategies and hotel revenue data to optimize yields.", duration: "3 months", stipend: "₹20,000/mo", tags: ["oyo", "finance", "data", "analytics"], location: "Gurgaon", workType: "Hybrid", role: "Revenue Analyst", url: "https://careers.oyorooms.com/" },
    { id: 152, org: "Groww", title: "Groww Product Management Intern", domain: "Product Management", desc: "Assist in roadmap planning and feature delivery for investment products.", duration: "6 months", stipend: "₹35,000/mo", tags: ["groww", "pm", "fintech"], location: "Bangalore", workType: "In Office", role: "Product Manager", url: "https://groww.in/about-us" },
    { id: 153, org: "ShareChat", title: "ShareChat Machine Learning Intern", domain: "AI/ML", desc: "Build advanced recommendation systems for regional content feeds.", duration: "6 months", stipend: "₹50,000/mo", tags: ["sharechat", "ml", "ai", "recommendation"], location: "Bangalore", workType: "Hybrid", role: "ML Engineer", url: "https://sharechat.com/about/careers" },
    { id: 154, org: "BharatPe", title: "BharatPe Cybersecurity Intern", domain: "Cybersecurity", desc: "Perform vulnerability assessments and strengthen payment infrastructure security.", duration: "3 months", stipend: "₹30,000/mo", tags: ["bharatpe", "cybersecurity", "security"], location: "Delhi", workType: "In Office", role: "Cybersecurity Analyst", url: "https://bharatpe.com/careers" },
    { id: 155, org: "Dunzo", title: "Dunzo Operations Intern", domain: "Logistics", desc: "Optimize delivery fleet operations and supply chain efficiency.", duration: "3 months", stipend: "₹20,000/mo", tags: ["dunzo", "operations", "logistics"], location: "Bangalore", workType: "In Office", role: "Operations Analyst", url: "https://www.dunzo.com/careers" },
    { id: 156, org: "Blinkit", title: "Blinkit UI/UX Intern", domain: "UI/UX Design", desc: "Design intuitive interfaces for 10-minute grocery delivery app.", duration: "3 months", stipend: "₹25,000/mo", tags: ["blinkit", "ui", "ux", "design"], location: "Gurgaon", workType: "Hybrid", role: "UI/UX Designer", url: "https://blinkit.com/careers" },
    { id: 157, org: "Upgrad", title: "Upgrad Marketing Intern", domain: "Marketing", desc: "Execute digital marketing campaigns and analyze user acquisition metrics.", duration: "3 months", stipend: "₹20,000/mo", tags: ["upgrad", "marketing", "digital"], location: "Mumbai", workType: "Hybrid", role: "Marketing Intern", url: "https://www.upgrad.com/careers/" },
    { id: 158, org: "Clear", title: "Clear Tax Tech Intern", domain: "Web Development", desc: "Develop and maintain robust web platforms for tax filing services.", duration: "6 months", stipend: "₹40,000/mo", tags: ["clear", "web", "frontend", "backend"], location: "Bangalore", workType: "In Office", role: "Full Stack Developer", url: "https://cleartax.in/s/careers" },
    { id: 159, org: "Urban Company", title: "Urban Company DevOps Intern", domain: "DevOps", desc: "Streamline CI/CD pipelines and monitor microservices deployment.", duration: "6 months", stipend: "₹35,000/mo", tags: ["urbancompany", "devops", "cloud"], location: "Gurgaon", workType: "In Office", role: "DevOps Engineer", url: "https://careers.urbancompany.com/" },
    { id: 160, org: "Pharmeasy", title: "Pharmeasy Data Science Intern", domain: "Data Science", desc: "Build predictive models for inventory management and demand forecasting.", duration: "3 months", stipend: "₹30,000/mo", tags: ["pharmeasy", "data", "ml"], location: "Mumbai", workType: "Hybrid", role: "Data Scientist", url: "https://pharmeasy.in/careers" },
    { id: 161, org: "Jio", title: "Jio 5G Networks Intern", domain: "Telecommunications", desc: "Research and develop network optimization tools for 5G infrastructure.", duration: "6 months", stipend: "₹25,000/mo", tags: ["jio", "telecom", "5g", "networking"], location: "Navi Mumbai", workType: "In Office", role: "Network Engineer", url: "https://careers.jio.com/" },
    { id: 162, org: "Airtel", title: "Airtel Digital Marketing Intern", domain: "Marketing", desc: "Assist in executing telecom growth marketing strategies and user engagement.", duration: "3 months", stipend: "₹15,000/mo", tags: ["airtel", "marketing", "digital"], location: "Gurgaon", workType: "Hybrid", role: "Marketing Analyst", url: "https://www.airtel.in/careers/" },
    { id: 163, org: "HDFC Bank", title: "HDFC Risk Analysis Intern", domain: "Finance", desc: "Analyze credit risk and develop statistical models for financial products.", duration: "2 months", stipend: "Paid", tags: ["hdfc", "finance", "risk"], location: "Mumbai", workType: "In Office", role: "Risk Analyst", url: "https://www.hdfcbank.com/about-us/careers" },
    { id: 164, org: "KPMG", title: "KPMG Cyber Security Consulting Intern", domain: "Cybersecurity", desc: "Assist in auditing and consulting clients on cybersecurity best practices.", duration: "3 months", stipend: "Paid", tags: ["kpmg", "cybersecurity", "consulting"], location: "Delhi", workType: "In Office", role: "Consultant", url: "https://kpmg.com/in/en/home/careers.html" },
    { id: 165, org: "PwC", title: "PwC Data Strategy Intern", domain: "Data Science", desc: "Provide data-driven insights and strategy consulting to enterprise clients.", duration: "3 months", stipend: "Paid", tags: ["pwc", "data", "strategy", "consulting"], location: "Bangalore", workType: "Hybrid", role: "Data Strategy Intern", url: "https://www.pwc.in/careers.html" },
    { id: 166, org: "EY", title: "EY Technology Risk Intern", domain: "Finance", desc: "Evaluate IT controls, assess risks and support audit engagements.", duration: "2 months", stipend: "Paid", tags: ["ey", "finance", "audit", "risk"], location: "Gurgaon", workType: "In Office", role: "Tech Risk Intern", url: "https://www.ey.com/en_in/careers" },
    { id: 167, org: "Bain & Company", title: "Bain Associate Consultant Intern", domain: "Management Consulting", desc: "Work alongside consultants to solve complex business challenges.", duration: "10 weeks", stipend: "Paid (premium)", tags: ["bain", "consulting", "strategy", "management"], location: "Mumbai", workType: "In Office", role: "Associate Consultant", url: "https://www.bain.com/careers/" },
    { id: 168, org: "BCG", title: "BCG Product Management Intern", domain: "Product Management", desc: "Drive digital product strategy and delivery across varying industries.", duration: "10 weeks", stipend: "Paid (premium)", tags: ["bcg", "pm", "consulting", "digital"], location: "Delhi", workType: "Hybrid", role: "Product Manager", url: "https://careers.bcg.com/" },
    { id: 169, org: "Siemens", title: "Siemens Automation Engineering Intern", domain: "Engineering", desc: "Develop software solutions for industrial automation and smart infrastructure.", duration: "6 months", stipend: "Paid", tags: ["siemens", "engineering", "automation"], location: "Pune", workType: "In Office", role: "Automation Engineer", url: "https://jobs.siemens.com/jobs" },
    { id: 170, org: "Bosch", title: "Bosch IoT Intern", domain: "Internet of Things", desc: "Create connected solutions and edge computing applications for smart devices.", duration: "6 months", stipend: "Paid", tags: ["bosch", "iot", "edge", "hardware"], location: "Bangalore", workType: "Hybrid", role: "IoT Developer", url: "https://careers.smartrecruiters.com/BoschGroup" },
    { id: 171, org: "General Electric", title: "GE Aviation Software Intern", domain: "Aviation/Tech", desc: "Develop critical software systems for aviation diagnostics and operations.", duration: "6 months", stipend: "Paid", tags: ["ge", "aviation", "software"], location: "Bangalore", workType: "In Office", role: "Software Developer", url: "https://jobs.gecareers.com/global/en" },
    { id: 172, org: "L&T", title: "L&T Civil Engineering Intern", domain: "Core Engineering", desc: "Gain hands-on experience in mega infrastructure and construction projects.", duration: "2 months", stipend: "₹10,000/mo", tags: ["lnt", "engineering", "infrastructure", "civil"], location: "Mumbai", workType: "In Office", role: "Civil Engineer", url: "https://www.larsentoubro.com/corporate/careers/" },
    { id: 173, org: "Reliance Industries", title: "Reliance Petrochemical Intern", domain: "Chemical Engineering", desc: "Work on process optimization and plant operations in petrochemicals.", duration: "2 months", stipend: "₹15,000/mo", tags: ["reliance", "chemical", "engineering"], location: "Jamnagar", workType: "In Office", role: "Process Engineer", url: "https://careers.ril.com/" },
    { id: 174, org: "Mahindra", title: "Mahindra Automotive Design Intern", domain: "Core Engineering", desc: "Assist in vehicle design, testing and EV development initiatives.", duration: "3 months", stipend: "₹15,000/mo", tags: ["mahindra", "automotive", "design", "ev"], location: "Chennai", workType: "In Office", role: "Design Engineer", url: "https://www.mahindra.com/careers" },
    { id: 175, org: "Tata Motors", title: "Tata Motors EV Tech Intern", domain: "Core Engineering", desc: "Research battery technologies and electric vehicle drivetrains.", duration: "6 months", stipend: "₹20,000/mo", tags: ["tata", "ev", "automotive", "engineering"], location: "Pune", workType: "In Office", role: "EV Engineer", url: "https://www.tatamotors.com/careers/" },
    { id: 176, org: "Maruti Suzuki", title: "Maruti Manufacturing Operations Intern", domain: "Core Engineering", desc: "Implement lean manufacturing and production optimization techniques.", duration: "2 months", stipend: "₹10,000/mo", tags: ["maruti", "manufacturing", "operations"], location: "Manesar", workType: "In Office", role: "Operations Engineer", url: "https://www.marutisuzuki.com/corporate/careers" },
    { id: 177, org: "HUL", title: "HUL Supply Chain Intern", domain: "Supply Chain", desc: "Work on logistics, demand planning and FMCG supply chain efficiency.", duration: "2 months", stipend: "Paid (premium)", tags: ["hul", "fmcg", "supply chain", "logistics"], location: "Mumbai", workType: "Hybrid", role: "Supply Chain Intern", url: "https://careers.unilever.com/india" },
    { id: 178, org: "ITC", title: "ITC Brand Management Intern", domain: "Marketing", desc: "Develop brand marketing campaigns and analyze consumer behavior.", duration: "2 months", stipend: "Paid", tags: ["itc", "fmcg", "marketing", "brand"], location: "Kolkata", workType: "In Office", role: "Brand Manager", url: "https://www.itcportal.com/careers/" },
    { id: 179, org: "Nestle", title: "Nestle Food Tech Intern", domain: "Research & Development", desc: "Assist in product development, quality assurance and food technology research.", duration: "6 months", stipend: "Paid", tags: ["nestle", "fmcg", "rnd", "food tech"], location: "Delhi", workType: "In Office", role: "Food Technologist", url: "https://www.nestle.in/jobs" },
    { id: 180, org: "P&G", title: "P&G Consumer Research Intern", domain: "Marketing", desc: "Conduct market research and implement data-driven marketing strategies.", duration: "2 months", stipend: "Paid", tags: ["png", "fmcg", "marketing", "research"], location: "Mumbai", workType: "Hybrid", role: "Consumer Researcher", url: "https://www.pgcareers.com/global/en/india-internships" },
    { id: 181, org: "Cognizant", title: "Cognizant Cloud Apps Intern", domain: "Cloud Computing", desc: "Develop and deploy cloud-native applications on AWS and Azure.", duration: "3 months", stipend: "₹20,000/mo", tags: ["cognizant", "cloud", "apps", "it"], location: "Chennai", workType: "In Office", role: "Cloud App Developer", url: "https://careers.cognizant.com/global/en" },
    { id: 182, org: "Wipro", title: "Wipro Cybersecurity Operations Intern", domain: "Cybersecurity", desc: "Monitor security events, perform triage and analyze threat intelligence.", duration: "6 months", stipend: "₹20,000/mo", tags: ["wipro", "cybersecurity", "security", "it"], location: "Bangalore", workType: "Hybrid", role: "Security Analyst", url: "https://careers.wipro.com/careers-home/" },
    { id: 183, org: "HCLTech", title: "HCL IoT & Embedded Sys Intern", domain: "Internet of Things", desc: "Work on embedded systems programming and IoT device integration.", duration: "6 months", stipend: "₹20,000/mo", tags: ["hcl", "iot", "embedded", "it"], location: "Noida", workType: "In Office", role: "Embedded Engineer", url: "https://www.hcltech.com/careers" },
    { id: 184, org: "Tech Mahindra", title: "Tech Mahindra AI/ML Intern", domain: "AI/ML", desc: "Develop enterprise AI solutions utilizing computer vision and NLP models.", duration: "3 months", stipend: "₹15,000/mo", tags: ["techmahindra", "ai", "ml", "it"], location: "Pune", workType: "In Office", role: "ML Engineer", url: "https://careers.techmahindra.com/" },
    { id: 185, org: "Capgemini", title: "Capgemini Data Analytics Intern", domain: "Data Science", desc: "Perform data wrangling and build dashboards for business intelligence.", duration: "3 months", stipend: "₹20,000/mo", tags: ["capgemini", "data", "analytics", "it"], location: "Mumbai", workType: "Hybrid", role: "Data Analyst", url: "https://www.capgemini.com/in-en/careers/" },
    { id: 186, org: "Accenture", title: "Accenture Strategy Tech Intern", domain: "Management Consulting", desc: "Contribute to enterprise architecture planning and IT strategy.", duration: "3 months", stipend: "Paid", tags: ["accenture", "strategy", "tech", "consulting"], location: "Bangalore", workType: "In Office", role: "Strategy Consultant", url: "https://www.accenture.com/in-en/careers" },
    { id: 187, org: "CGI", title: "CGI Full Stack Intern", domain: "Web Development", desc: "Develop responsive web platforms using Java, Spring Boot, and Angular.", duration: "6 months", stipend: "₹25,000/mo", tags: ["cgi", "fullstack", "java", "angular"], location: "Bangalore", workType: "In Office", role: "Full Stack Developer", url: "https://www.cgi.com/india/en/careers" },
    { id: 188, org: "Mindtree", title: "Mindtree Cloud Migration Intern", domain: "Cloud Computing", desc: "Assist in migrating legacy on-premise applications to modern cloud architecture.", duration: "3 months", stipend: "₹20,000/mo", tags: ["mindtree", "ltimindtree", "cloud", "migration"], location: "Bangalore", workType: "Hybrid", role: "Cloud Engineer", url: "https://www.ltimindtree.com/careers/" },
    { id: 189, org: "Hexaware", title: "Hexaware Automation Testing Intern", domain: "Quality Assurance", desc: "Design test cases and build automation scripts using Selenium.", duration: "6 months", stipend: "₹15,000/mo", tags: ["hexaware", "testing", "qa", "automation"], location: "Chennai", workType: "In Office", role: "QA Engineer", url: "https://hexaware.com/careers/" },
    { id: 190, org: "Zensar", title: "Zensar UI/UX Research Intern", domain: "UI/UX Design", desc: "Conduct user research and create wireframes for enterprise software interfaces.", duration: "3 months", stipend: "₹15,000/mo", tags: ["zensar", "ui", "ux", "research", "design"], location: "Pune", workType: "Hybrid", role: "UX Researcher", url: "https://www.zensar.com/careers" }
];

const CAREER_DATA_PATH = '/Users/anukritisrivastava/Desktop/TECHYYYYY/StudentSupport/DecisionSupportSystemForStudent/decision-support-system-for-students/src/data/careerData.js';
const OPPORTUNITY_FETCHER_PATH = '/Users/anukritisrivastava/Desktop/TECHYYYYY/StudentSupport/DecisionSupportSystemForStudent/server/services/opportunityFetcher.js';

let careerData = fs.readFileSync(CAREER_DATA_PATH, 'utf-8');
let oppFetcher = fs.readFileSync(OPPORTUNITY_FETCHER_PATH, 'utf-8');

// 1. Process MOCK_INTERNSHIPS in careerData.js
// Find the end of MOCK_INTERNSHIPS: `];` after id 138.
let newMockInternshipsString = newInternships.map(i => {
    return `  { id: ${i.id}, org: "${i.org}", title: "${i.title}", domain: "${i.domain}", desc: "${i.desc}", duration: "${i.duration}", stipend: "${i.stipend}", tags: ${JSON.stringify(i.tags)}, location: "${i.location}", workType: "${i.workType}", role: "${i.role}", datePosted: "2024-03-25" },`;
}).join('\n');

careerData = careerData.replace(
    /(\s*\{\s*id:\s*138[^\}]+\},)\n\];/g,
    `$1\n${newMockInternshipsString}\n];`
);

// 2. Process INTERNSHIP_URLS in careerData.js
let newInternshipUrlsString = newInternships.map(i => {
    return `  ${i.id}: "${i.url}",`;
}).join('\n');

careerData = careerData.replace(
    /(\s*138:\s*"[^"]+",)\n\};/g,
    `$1\n${newInternshipUrlsString}\n};`
);

fs.writeFileSync(CAREER_DATA_PATH, careerData, 'utf-8');

// 3. Process INTERNSHIPS in opportunityFetcher.js
let newFetcherInternshipsString = newInternships.map(i => {
    return `  { id:${i.id}, title:"${i.title}", org:"${i.org}", domain:"${i.domain}", desc:"${i.desc}", url:"${i.url}", duration:"${i.duration}", stipend:"${i.stipend}", location:"${i.location}", workType:"${i.workType}", role:"${i.role}", tags:${JSON.stringify(i.tags)} },`;
}).join('\n');

oppFetcher = oppFetcher.replace(
    /(\s*\{\s*id:138[^\}]+\},)\n\];/g,
    `$1\n${newFetcherInternshipsString}\n];`
);

fs.writeFileSync(OPPORTUNITY_FETCHER_PATH, oppFetcher, 'utf-8');

console.log('Successfully updated the files with 52 new internships!');
