/**
 * opportunityFetcher.js
 * Seeds the OpportunityCatalog collection from the curated dataset.
 * Uses updateOne + upsert so it is fully idempotent — safe to run on every boot.
 * Deduplication key: { title, type } (enforced by DB index + upsert logic).
 */

const OpportunityCatalog = require('../models/OpportunityCatalog');

// ─── Curated competitions dataset ────────────────────────────────────────────
const COMPETITIONS = [
  // Hackathons
  { id:1,  title:"Smart India Hackathon (SIH)",             category:"hackathon", org:"Ministry of Education",    domain:"All Domains",          desc:"India's largest national-level hackathon solving government problem statements across 36 hours.", url:"https://www.sih.gov.in",              status:"Live",    eventType:"Offline", payment:"Free", teamSize:"2+", tags:["hack","sih","government","national"] },
  { id:2,  title:"HackFest 2026",                           category:"hackathon", org:"HackFest",                 domain:"Web Development",       desc:"48-hour hackathon focused on building social impact solutions using modern web stack.",            url:"https://hackfest.dev",                status:"Live",    eventType:"Online",  payment:"Free", teamSize:"2+", tags:["hack","web","social"] },
  { id:3,  title:"HackCBS",                                 category:"hackathon", org:"Shaheed Sukhdev College",  domain:"Open Innovation",       desc:"Delhi's biggest student-run hackathon with 36 hours of hacking.",                               url:"https://hackcbs.tech",                status:"Closed",  eventType:"Offline", payment:"Paid", teamSize:"2+", tags:["hack","delhi","student"] },
  { id:4,  title:"MLH Global Hack Week",                    category:"hackathon", org:"Major League Hacking",     domain:"Open Source & Tech",    desc:"Week-long themed hacking events run by MLH covering diverse tech topics.",                       url:"https://ghw.mlh.io",                  status:"Recent",  eventType:"Online",  payment:"Free", teamSize:"1",  tags:["hack","mlh","open source"] },
  { id:5,  title:"AngelHack Global Hackathon",              category:"hackathon", org:"AngelHack",                domain:"FinTech & Startup",     desc:"Global series with prizes for the most innovative startup ideas and prototypes.",                url:"https://angelhack.com/hackglobal",    status:"Live",    eventType:"Online",  payment:"Free", teamSize:"2+", tags:["hack","startup","fintech","global"] },
  { id:6,  title:"StackHack",                               category:"hackathon", org:"HackerEarth",              domain:"Full Stack Development",desc:"Online hackathon for full-stack engineers with real-world problem statements.",                   url:"https://www.hackerearth.com/challenges/hackathon/stackhack", status:"Expired", eventType:"Online",  payment:"Free", teamSize:"1",  tags:["hack","fullstack","hackerearth"] },
  { id:7,  title:"Google Solution Challenge",               category:"hackathon", org:"Google",                   domain:"Social Impact + AI",    desc:"Build solutions for UN Sustainable Development Goals using Google technology.",                  url:"https://developers.google.com/community/gdsc-solution-challenge", status:"Live", eventType:"Online",  payment:"Free", teamSize:"2+", tags:["hack","google","sdg","ai"] },
  { id:8,  title:"Microsoft Imagine Cup",                   category:"hackathon", org:"Microsoft",                domain:"Innovation",            desc:"Global student tech competition across AI, gaming, and mixed reality.",                          url:"https://imaginecup.microsoft.com",    status:"Live",    eventType:"Offline", payment:"Free", teamSize:"2+", tags:["hack","microsoft","global","student"] },
  { id:9,  title:"ETHIndia",                                category:"hackathon", org:"ETHIndia",                 domain:"Blockchain / Web3",     desc:"India's largest Ethereum hackathon for building decentralised applications.",                   url:"https://ethindia.co",                 status:"Closed",  eventType:"Offline", payment:"Paid", teamSize:"2+", tags:["hack","blockchain","web3","ethereum"] },
  { id:10, title:"Devfolio Hackathons",                     category:"hackathon", org:"Devfolio",                 domain:"Open Innovation",       desc:"Hundreds of college and online hackathons on India's largest hackathon platform.",              url:"https://devfolio.co/hackathons",      status:"Live",    eventType:"Online",  payment:"Free", teamSize:"2+", tags:["hack","devfolio","india","college"] },
  { id:11, title:"NASA Space Apps Challenge",               category:"hackathon", org:"NASA",                     domain:"Space & Science",       desc:"Global hackathon solving space-related challenges using NASA open data.",                        url:"https://www.spaceappschallenge.org",   status:"Recent",  eventType:"Hybrid",  payment:"Free", teamSize:"2+", tags:["hack","nasa","space","science","global"] },
  { id:12, title:"HackaHealth",                             category:"hackathon", org:"HackaHealth",              domain:"HealthTech",            desc:"Healthcare-focused hackathon using technology to solve health challenges.",                      url:"https://hackahealth.devpost.com",     status:"Live",    eventType:"Offline", payment:"Free", teamSize:"2+", tags:["hack","health","healthcare"] },
  { id:13, title:"Fintech Hackathon by RBI",                category:"hackathon", org:"Reserve Bank of India",    domain:"FinTech",               desc:"Regulator-run hackathon for next-gen financial tech solutions for India.",                      url:"https://rbi.org.in/scripts/hackathon.aspx", status:"Live", eventType:"Offline", payment:"Free", teamSize:"2+", tags:["hack","fintech","rbi","finance"] },
  { id:14, title:"HackThis Fall",                           category:"hackathon", org:"HackThis Fall",            domain:"Open Source",           desc:"Inclusivity-first 36-hour online hackathon open to students from all backgrounds.",             url:"https://hackthisfall.tech",           status:"Recent",  eventType:"Online",  payment:"Free", teamSize:"1",  tags:["hack","open source","online","beginner"] },
  // Coding
  { id:15, title:"Google Code Jam",                         category:"coding",    org:"Google",                   domain:"Algorithms & DSA",      desc:"Google's legendary algorithmic programming competition open to coders worldwide.",               url:"https://codingcompetitions.withgoogle.com/codejam",           status:"Live",    eventType:"Online",  payment:"Free", teamSize:"1",  tags:["coding","competitive","algorithm","google"] },
  { id:16, title:"Meta Hacker Cup",                         category:"coding",    org:"Meta",                     domain:"Algorithms & DSA",      desc:"Annual worldwide programming competition hosted by Meta.",                                      url:"https://www.facebook.com/codingcompetitions/hacker-cup",      status:"Live",    eventType:"Online",  payment:"Free", teamSize:"1",  tags:["coding","competitive","algorithm","meta","facebook"] },
  { id:17, title:"ICPC",                                    category:"coding",    org:"ICPC Foundation",          domain:"Algorithms & DSA",      desc:"The world's oldest and most prestigious collegiate programming contest.",                       url:"https://icpc.global",                 status:"Live",    eventType:"Offline", payment:"Paid", teamSize:"2+", tags:["coding","competitive","icpc","college","algorithm"] },
  { id:18, title:"CodeChef Long Challenge",                 category:"coding",    org:"CodeChef",                 domain:"Algorithms & DSA",      desc:"10-day monthly contest with diverse algorithmic problems of varying difficulty.",               url:"https://www.codechef.com/LTIME",      status:"Live",    eventType:"Online",  payment:"Free", teamSize:"1",  tags:["coding","competitive","codechef","algorithm"] },
  { id:19, title:"Codeforces Global Round",                 category:"coding",    org:"Codeforces",               domain:"Competitive Programming",desc:"High-rated global competition attracting top competitive programmers.",                        url:"https://codeforces.com",              status:"Live",    eventType:"Online",  payment:"Free", teamSize:"1",  tags:["coding","competitive","codeforces","algorithm","cp"] },
  { id:20, title:"LeetCode Weekly Contest",                 category:"coding",    org:"LeetCode",                 domain:"Algorithms & DSA",      desc:"Weekly timed contests testing problem-solving across arrays, trees, graphs and DP.",            url:"https://leetcode.com/contest",        status:"Live",    eventType:"Online",  payment:"Free", teamSize:"1",  tags:["coding","leetcode","algorithm","dsa"] },
  { id:21, title:"HackerRank Certification Challenge",      category:"coding",    org:"HackerRank",               domain:"Algorithms & DSA",      desc:"Solve problems to earn industry-recognised skill certifications.",                             url:"https://www.hackerrank.com/skills-verification", status:"Live", eventType:"Online", payment:"Free", teamSize:"1", tags:["coding","hackerrank","certification","algorithm"] },
  { id:22, title:"Kickstart by Google",                     category:"coding",    org:"Google",                   domain:"Algorithms & DSA",      desc:"Round-based algorithmic challenge by Google — a pathway into Google internships.",              url:"https://codingcompetitions.withgoogle.com/kickstart",         status:"Recent",  eventType:"Online",  payment:"Free", teamSize:"1",  tags:["coding","google","kickstart","algorithm","internship"] },
  { id:23, title:"AtCoder Grand Contest",                   category:"coding",    org:"AtCoder",                  domain:"Competitive Programming",desc:"Premier competitive programming contest from Japan with highly challenging problems.",           url:"https://atcoder.jp",                  status:"Live",    eventType:"Online",  payment:"Free", teamSize:"1",  tags:["coding","competitive","atcoder","algorithm"] },
  { id:24, title:"CodeForces Div. 2 Contest",               category:"coding",    org:"Codeforces",               domain:"Competitive Programming",desc:"Regular contest for intermediate competitive programmers featuring 5-6 problems.",              url:"https://codeforces.com/contests",     status:"Live",    eventType:"Online",  payment:"Free", teamSize:"1",  tags:["coding","competitive","codeforces","cp"] },
  // Olympiads
  { id:25, title:"International Olympiad in Informatics (IOI)", category:"olympiad", org:"IOI Committee",         domain:"Computer Science",      desc:"Most prestigious programming olympiad for high school students globally.",                      url:"https://ioinformatics.org",           status:"Live",    eventType:"Offline", payment:"Paid", teamSize:"1",  tags:["olympiad","ioi","informatics","student"] },
  { id:26, title:"International Mathematical Olympiad (IMO)",   category:"olympiad", org:"IMO Committee",         domain:"Mathematics",           desc:"World championship mathematics competition for pre-university students.",                      url:"https://www.imo-official.org",        status:"Live",    eventType:"Offline", payment:"Paid", teamSize:"1",  tags:["olympiad","imo","math","mathematics"] },
  { id:27, title:"ZIO / INOI (Indian Computing Olympiad)",      category:"olympiad", org:"IARCS",                 domain:"Computer Science",      desc:"India's national computing olympiad — pathway to IOI representation.",                        url:"https://www.iarcs.org.in/inoi",       status:"Recent",  eventType:"Online",  payment:"Paid", teamSize:"1",  tags:["olympiad","zio","inoi","india","informatics"] },
  { id:28, title:"RMO / INMO (Indian Math Olympiad)",           category:"olympiad", org:"HBCSE",                 domain:"Mathematics",           desc:"Regional and national math olympiad — gateway to IMO for Indian students.",                   url:"https://olympiads.hbcse.tifr.res.in/which-olympiads/maths", status:"Live", eventType:"Offline", payment:"Paid", teamSize:"1", tags:["olympiad","rmo","inmo","math","india"] },
  { id:29, title:"Science Olympiad Foundation (SOF)",           category:"olympiad", org:"SOF",                   domain:"Science & Math",        desc:"Multi-subject olympiad exams covering science, math, and CS for school students.",             url:"https://sofworld.org",                status:"Live",    eventType:"Offline", payment:"Paid", teamSize:"1",  tags:["olympiad","sof","science","school"] },
  { id:30, title:"International Physics Olympiad (IPhO)",       category:"olympiad", org:"IPhO Committee",        domain:"Physics",               desc:"Global physics competition featuring theoretical and experimental challenges.",                 url:"https://ipho-new.org",                status:"Live",    eventType:"Offline", payment:"Paid", teamSize:"1",  tags:["olympiad","physics","ipho","global"] },
  // Data Science
  { id:31, title:"Kaggle Featured Competition", category:"data", org:"Kaggle / Google", domain:"Data Science", desc:"Solve real-world ML problems with massive datasets. Top solutions win cash prizes.", url:"https://www.kaggle.com/competitions", status:"Live", eventType:"Online", payment:"Free", teamSize:"1", tags:["data","kaggle","ml","data science","competition"] },
  { id:32, title:"Analytics Vidhya Hackathon", category:"data", org:"Analytics Vidhya", domain:"Data Science", desc:"India's largest data science hackathons with industry-grade datasets and mentorship.", url:"https://datahack.analyticsvidhya.com", status:"Live", eventType:"Online", payment:"Free", teamSize:"1", tags:["data","analytics","datathon","india","ml"] },
  { id:33, title:"DrivenData Competition",     category:"data", org:"DrivenData",       domain:"Data for Social Good", desc:"Data science competitions focused on social impact — health, education, disaster response.", url:"https://www.drivendata.org/competitions", status:"Live", eventType:"Online", payment:"Free", teamSize:"1", tags:["data","social","ml","driven data"] },
  { id:34, title:"Zindi Africa ML Challenge",  category:"data", org:"Zindi",            domain:"Machine Learning",     desc:"ML competitions focused on African datasets — agriculture, health, finance.", url:"https://zindi.africa/competitions", status:"Live", eventType:"Online", payment:"Free", teamSize:"1", tags:["data","ml","africa","zindi"] },
  { id:35, title:"MachineHack Data Challenge", category:"data", org:"MachineHack",      domain:"Data Science",         desc:"Practice-oriented data science challenges covering regression, NLP, and CV.", url:"https://machinehack.com/hackathons", status:"Live", eventType:"Online", payment:"Free", teamSize:"1", tags:["data","machinehack","ml","practice"] },
  // AI
  { id:36, title:"Google AI Challenge",              category:"ai", org:"Google",    domain:"Artificial Intelligence",   desc:"Build innovative AI solutions using Google TensorFlow and cloud AI platform.", url:"https://ai.google.dev/competition",                              status:"Live",   eventType:"Online", payment:"Free", teamSize:"2+", tags:["ai","google","tensorflow","ml"] },
  { id:37, title:"Microsoft AI for Good Challenge",  category:"ai", org:"Microsoft", domain:"AI for Social Impact",      desc:"Use AI and Azure to solve global challenges in sustainability and accessibility.", url:"https://www.microsoft.com/en-us/ai/ai-for-good",                status:"Live",   eventType:"Online", payment:"Free", teamSize:"2+", tags:["ai","microsoft","azure","social"] },
  { id:38, title:"NVIDIA AI Contest",                category:"ai", org:"NVIDIA",    domain:"Deep Learning",             desc:"Build GPU-accelerated deep learning applications using NVIDIA tools.", url:"https://developer.nvidia.com/blog/tag/competition",              status:"Live",   eventType:"Online", payment:"Free", teamSize:"1",  tags:["ai","nvidia","deep learning","gpu","cuda"] },
  { id:39, title:"Amazon SageMaker ML Challenge",    category:"ai", org:"Amazon",    domain:"Machine Learning",          desc:"End-to-end ML pipeline challenge using Amazon SageMaker and AWS.", url:"https://aws.amazon.com/sagemaker/jumpstart",                     status:"Recent", eventType:"Online", payment:"Free", teamSize:"1",  tags:["ai","amazon","sagemaker","ml","aws"] },
  { id:40, title:"OpenAI Evals Challenge",           category:"ai", org:"OpenAI",    domain:"LLMs & GenAI",              desc:"Create evaluation benchmarks for large language models. Contribute to AI safety.", url:"https://github.com/openai/evals",                             status:"Live",   eventType:"Online", payment:"Free", teamSize:"1",  tags:["ai","openai","llm","genai","safety"] },
  // Design
  { id:41, title:"Adobe Creative Jam",       category:"design", org:"Adobe",    domain:"UI/UX Design",   desc:"Fast-paced design challenge creating innovative prototypes using Adobe XD.", url:"https://www.behance.net/adobe-creative-jam", status:"Live",   eventType:"Hybrid",  payment:"Free", teamSize:"2+", tags:["design","adobe","ui","ux","creative"] },
  { id:42, title:"UX Challenge by Google",   category:"design", org:"Google",   domain:"User Experience",desc:"Solve real-world UX problems for Google products.",                           url:"https://uxdesign.cc/ux-challenge",           status:"Live",   eventType:"Online",  payment:"Free", teamSize:"1",  tags:["design","google","ux","product"] },
  { id:43, title:"Figma Config Design Challenge",category:"design",org:"Figma",  domain:"Product Design", desc:"Annual design challenge during Figma Config — build the best plugin or prototype.", url:"https://www.figma.com/community/plugins", status:"Recent", eventType:"Online",  payment:"Free", teamSize:"1",  tags:["design","figma","prototype","plugin"] },
  { id:44, title:"Dribbble Design Sprint",   category:"design", org:"Dribbble", domain:"Visual Design",   desc:"Weekly creative sprints — build portfolios and win recognition.",               url:"https://dribbble.com",                       status:"Live",   eventType:"Online",  payment:"Free", teamSize:"1",  tags:["design","dribbble","visual","portfolio"] },
  { id:45, title:"Canva Design Awards",      category:"design", org:"Canva",    domain:"Graphic Design",  desc:"Submit your best Canva designs for global recognition and prizes.",               url:"https://www.canva.com/design-awards",        status:"Live",   eventType:"Online",  payment:"Free", teamSize:"1",  tags:["design","canva","graphic","creative"] },
  // Business
  { id:46, title:"Hult Prize",                   category:"business", org:"Hult Prize Foundation", domain:"Social Entrepreneurship",desc:"World's largest student competition for social enterprise. $1M prize.", url:"https://www.hultprize.org",      status:"Live", eventType:"Offline", payment:"Paid", teamSize:"2+", tags:["business","startup","social","hult"] },
  { id:47, title:"E-Cell IIT Bombay Eureka!",    category:"business", org:"IIT Bombay",            domain:"Startup & Business",     desc:"Asia's largest business model competition for student entrepreneurs.",  url:"https://ecell.in/eureka",         status:"Live", eventType:"Hybrid",  payment:"Free", teamSize:"2+", tags:["business","startup","iit","eureka","entrepreneur"] },
  { id:48, title:"Shark Tank India Campus Edition",category:"business",org:"Sony / SonyLIV",       domain:"Startup Pitch",          desc:"Campus edition of Shark Tank India — pitch your startup to real investors.", url:"https://www.sharktankindia.com", status:"Live", eventType:"Offline", payment:"Free", teamSize:"2+", tags:["business","startup","shark tank","pitch","investor"] },
  { id:49, title:"TiE Young Entrepreneurs",      category:"business", org:"TiE Global",            domain:"Entrepreneurship",       desc:"Mentorship and competition for young entrepreneurs aged 14-25.",       url:"https://www.tie.org/programs/tye", status:"Live", eventType:"Hybrid",  payment:"Free", teamSize:"1",  tags:["business","startup","tie","youth","entrepreneur"] },
  { id:50, title:"CFA Institute Research Challenge",category:"business",org:"CFA Institute",        domain:"Finance & Equity Research",desc:"Students analyse a public company and present investment recommendations.", url:"https://rpc.cfainstitute.org",  status:"Live", eventType:"Hybrid",  payment:"Paid", teamSize:"2+", tags:["business","finance","cfa","equity","research"] },
];

// ─── Curated internships dataset ─────────────────────────────────────────────
const INTERNSHIPS = [
  { id:101, title:"Google Summer of Code (GSoC)",          org:"Google",       domain:"Open Source",          desc:"3-month paid programme working on open source projects mentored by Google engineers.", url:"https://summerofcode.withgoogle.com",                                                    duration:"3 months",  stipend:"₹60,000+/mo", location:"Remote",         workType:"Work from Home", role:"Open Source", tags:["google","open source","coding","paid","summer"] },
  { id:102, title:"Google STEP Internship",                org:"Google",       domain:"Software Engineering",  desc:"Student Training in Engineering Program for 1st and 2nd year CS students.",            url:"https://buildyourfuture.withgoogle.com/programs/step",                                  duration:"3 months",  stipend:"Paid",         location:"Bangalore",      workType:"In Office",      role:"SDE", tags:["google","engineering","student","first year"] },
  { id:103, title:"Google Research Internship",            org:"Google",       domain:"AI / Research",         desc:"Research internships across Google Brain, DeepMind and Google Research labs.",        url:"https://research.google/programs-and-events",                                           duration:"3-6 months",stipend:"Paid",         location:"Hyderabad",      workType:"Hybrid",         role:"AI Research", tags:["google","research","ai","deepmind","ml"] },
  { id:104, title:"Microsoft Explore Internship",          org:"Microsoft",    domain:"Software Engineering",  desc:"Internship for freshmen/sophomore students exploring PM, design, and engineering.",   url:"https://careers.microsoft.com/students/us/en/usexploremicrosoftprogram",                duration:"12 weeks",  stipend:"Paid",         location:"Hyderabad",      workType:"In Office",      role:"Product Management", tags:["microsoft","engineering","explore","pm","student"] },
  { id:105, title:"Microsoft Azure Cloud Internship",      org:"Microsoft",    domain:"Cloud Computing",       desc:"Work on Azure services and cloud infrastructure at Microsoft.",                       url:"https://careers.microsoft.com/students/us/en/job/azure-internships",                   duration:"3 months",  stipend:"Paid",         location:"Bangalore",      workType:"Hybrid",         role:"Cloud Engineering", tags:["microsoft","azure","cloud","infra"] },
  { id:106, title:"Microsoft Research Asia Internship",    org:"Microsoft",    domain:"AI / Research",         desc:"Research internship at MSRA on NLP, CV, Distributed Systems, and Security.",        url:"https://www.microsoft.com/en-us/research/academic-program/research-internships-asia", duration:"3-6 months",stipend:"Paid",         location:"Remote",         workType:"Work from Home", role:"Applied AI", tags:["microsoft","research","ai","nlp","asia"] },
  { id:107, title:"Amazon SDE Internship",                 org:"Amazon",       domain:"Software Development",  desc:"Build real features at Amazon with a team. Work on AWS, Alexa, or Amazon retail.",  url:"https://www.amazon.jobs/en/jobs/internships",                                           duration:"3 months",  stipend:"Paid",         location:"Pune",           workType:"In Office",      role:"SDE", tags:["amazon","sde","aws","software","engineering"] },
  { id:108, title:"AWS Solutions Architect Intern",        org:"Amazon",       domain:"Cloud Computing",       desc:"Design and implement cloud solutions for AWS customers.",                            url:"https://aws.amazon.com/careers/internships",                                            duration:"3 months",  stipend:"Paid",         location:"Mumbai",         workType:"Hybrid",         role:"Cloud Solutions", tags:["amazon","aws","cloud","architect","solutions"] },
  { id:109, title:"Meta Software Engineer Internship",     org:"Meta",         domain:"Software Engineering",  desc:"Work on Facebook, Instagram, WhatsApp or Oculus products.",                          url:"https://www.metacareers.com/students",                                                  duration:"12 weeks",  stipend:"Paid",         location:"Remote",         workType:"Work from Home", role:"SDE", tags:["meta","facebook","instagram","engineering","software"] },
  { id:110, title:"Apple iOS Engineering Internship",      org:"Apple",        domain:"iOS Development",        desc:"Contribute to iOS, macOS, watchOS platforms and first-party apps at Apple.",       url:"https://www.apple.com/jobs/us/internships.html",                                        duration:"3 months",  stipend:"Paid",         location:"Hyderabad",      workType:"In Office",      role:"iOS Development", tags:["apple","ios","swift","engineering","mac"] },
  { id:111, title:"Netflix Engineering Internship",        org:"Netflix",      domain:"Software Engineering",  desc:"Work on streaming infrastructure, recommendation systems or UX at Netflix.",        url:"https://jobs.netflix.com/work-life-philosophy/students",                                duration:"3 months",  stipend:"Paid (top tier)",location:"Mumbai",        workType:"Hybrid",         role:"Backend Engineering", tags:["netflix","streaming","engineering","recommendation","ml"] },
  { id:112, title:"Adobe Research Internship",             org:"Adobe",        domain:"AI / Creative Tech",    desc:"Work on AI, computer vision and creative technology research at Adobe Research.",  url:"https://adobe.com/careers",                                                             duration:"3 months",  stipend:"Paid",         location:"Noida",          workType:"In Office",      role:"Computer Vision", tags:["adobe","research","ai","creative","cv","design"] },
  { id:113, title:"Salesforce Intern",                     org:"Salesforce",   domain:"Cloud CRM",             desc:"Build and test features for Salesforce CRM platform and ecosystem.",                url:"https://careers.salesforce.com/en/programs/futureforce",                                duration:"3 months",  stipend:"Paid",         location:"Hyderabad",      workType:"Hybrid",         role:"Cloud CRM", tags:["salesforce","crm","cloud","enterprise","business"] },
  { id:114, title:"LinkedIn Engineering Internship",       org:"LinkedIn",     domain:"Software Engineering",  desc:"Work on LinkedIn's professional network platform, search, feed or data infra.",    url:"https://careers.linkedin.com/students",                                                 duration:"3 months",  stipend:"Paid",         location:"Bangalore",      workType:"In Office",      role:"SDE", tags:["linkedin","engineering","data","networking","software"] },
  { id:115, title:"Razorpay SDE Intern",                   org:"Razorpay",     domain:"FinTech",               desc:"Build payment infrastructure powering millions of Indian businesses.",              url:"https://razorpay.com/jobs",                                                             duration:"3 months",  stipend:"₹40,000/mo",  location:"Bangalore",      workType:"In Office",      role:"SDE", tags:["razorpay","fintech","sde","payments","startup"] },
  { id:116, title:"CRED Product Design Intern",            org:"CRED",         domain:"UI/UX Design",          desc:"Design premium experiences for India's most design-forward fintech app.",           url:"https://careers.cred.club",                                                             duration:"3 months",  stipend:"₹35,000/mo",  location:"Bangalore",      workType:"Hybrid",         role:"UI/UX Design", tags:["cred","design","ui","ux","fintech"] },
  { id:117, title:"Zerodha Backend Engineering Intern",    org:"Zerodha",      domain:"FinTech",               desc:"Work on high-frequency trading systems and financial data pipelines.",              url:"https://zerodha.com/careers",                                                           duration:"6 months",  stipend:"₹50,000/mo",  location:"Bangalore",      workType:"In Office",      role:"Backend Engineering", tags:["zerodha","fintech","backend","trading","finance"] },
  { id:118, title:"Swiggy Data Science Intern",            org:"Swiggy",       domain:"Data Science",          desc:"Optimise delivery logistics, demand forecasting and recommendation engines at scale.", url:"https://careers.swiggy.com",                                                       duration:"3 months",  stipend:"₹30,000/mo",  location:"Bangalore",      workType:"Hybrid",         role:"Data Science", tags:["swiggy","data","ml","logistics","recommendation"] },
  { id:119, title:"Zomato Full Stack Intern",              org:"Zomato",       domain:"Web Development",       desc:"Build customer and restaurant-facing features for India's largest food-tech.",      url:"https://www.zomato.com/careers",                                                        duration:"3 months",  stipend:"₹25,000/mo",  location:"Gurgaon",        workType:"In Office",      role:"Full Stack", tags:["zomato","fullstack","web","food tech"] },
  { id:120, title:"Flipkart SDE Intern",                   org:"Flipkart",     domain:"E-Commerce",            desc:"Engineer scalable systems for India's leading e-commerce marketplace.",              url:"https://www.flipkartcareers.com",                                                       duration:"3 months",  stipend:"₹45,000/mo",  location:"Bangalore",      workType:"In Office",      role:"SDE", tags:["flipkart","sde","ecommerce","engineering"] },
  { id:121, title:"Atlassian Engineering Intern",          org:"Atlassian",    domain:"DevOps & Productivity", desc:"Work on Jira, Confluence, Bitbucket and other developer productivity tools.",       url:"https://www.atlassian.com/company/careers/interns",                                     duration:"3 months",  stipend:"Paid",         location:"Bangalore",      workType:"Hybrid",         role:"SDE", tags:["atlassian","devops","jira","sde","tools"] },
  { id:122, title:"PhonePe Android Intern",                org:"PhonePe",      domain:"Mobile Development",    desc:"Build UPI payment features on India's most used payments app.",                     url:"https://phonepe.com/en/careers.html",                                                   duration:"3 months",  stipend:"₹35,000/mo",  location:"Bangalore",      workType:"In Office",      role:"Mobile Development", tags:["phonepe","android","mobile","upi","fintech"] },
  { id:123, title:"ISRO Research Internship",              org:"ISRO",         domain:"Space & Research",      desc:"Work on satellite systems, propulsion or space science at India's premier space agency.", url:"https://www.isro.gov.in/Internship.html",                                       duration:"2 months",  stipend:"₹10,000/mo",  location:"Bangalore",      workType:"In Office",      role:"Research", tags:["isro","research","space","science","government"] },
  { id:124, title:"DRDO Internship Programme",             org:"DRDO",         domain:"Defence Technology",    desc:"Contribute to defence research projects in electronics, AI and aerospace.",          url:"https://www.drdo.gov.in/internship-programme",                                          duration:"2 months",  stipend:"₹10,000/mo",  location:"Delhi",          workType:"In Office",      role:"Research", tags:["drdo","defence","research","government","engineering"] },
  { id:125, title:"Deloitte Consulting Intern",            org:"Deloitte",     domain:"Management Consulting", desc:"Work on strategy, operations and technology consulting for Fortune 500 clients.",   url:"https://careers.deloitte.com/students",                                                 duration:"3 months",  stipend:"₹40,000/mo",  location:"Mumbai",         workType:"In Office",      role:"Consulting", tags:["deloitte","consulting","business","strategy","management"] },
  { id:126, title:"McKinsey Digital Intern",               org:"McKinsey & Company",domain:"Tech Consulting",  desc:"Support digital transformation engagements combining strategy with tech.",          url:"https://www.mckinsey.com/careers/students",                                             duration:"10 weeks",  stipend:"Paid (premium)",location:"Gurgaon",       workType:"In Office",      role:"Consulting", tags:["mckinsey","consulting","digital","strategy","tech"] },
  { id:127, title:"Goldman Sachs Engineering Intern",      org:"Goldman Sachs",domain:"FinTech / Banking",     desc:"Build trading systems, risk platforms and internal tools at a top investment bank.", url:"https://www.goldmansachs.com/careers/students",                                        duration:"10 weeks",  stipend:"Paid",         location:"Bangalore",      workType:"Hybrid",         role:"SDE", tags:["goldman","finance","banking","sde","engineering"] },
  { id:128, title:"JPMorgan Software Engineering Intern",  org:"JPMorgan Chase",domain:"Banking Technology",   desc:"Develop tech solutions for one of the world's largest financial institutions.",     url:"https://careers.jpmorgan.com/us/en/students/programs",                                 duration:"10 weeks",  stipend:"Paid",         location:"Mumbai",         workType:"In Office",      role:"SDE", tags:["jpmorgan","finance","banking","sde","engineering"] },
  { id:129, title:"TCS Digital Intern",                    org:"Tata Consultancy Services",domain:"IT & Consulting", desc:"Work on enterprise digital transformation projects across diverse industries.", url:"https://ibegin.tcs.com/iBegin/#/home",                                          duration:"3 months",  stipend:"₹15,000/mo",  location:"Multiple Cities",workType:"Hybrid",         role:"IT Consulting", tags:["tcs","it","digital","consulting","enterprise"] },
  { id:130, title:"Infosys InStep Internship",             org:"Infosys",      domain:"IT & Innovation",       desc:"Premier global internship programme focused on emerging tech research and innovation.", url:"https://www.infosys.com/instep",                                                   duration:"3 months",  stipend:"₹25,000/mo",  location:"Bangalore",      workType:"In Office",      role:"Innovation & Research", tags:["infosys","it","innovation","research","instep"] },
  { id:131, title:"Unacademy Frontend Intern",             org:"Unacademy",    domain:"EdTech",                desc:"Build interactive learning experiences for millions of students on India's top edtech platform.", url:"https://unacademy.com/careers",                                       duration:"3 months",  stipend:"₹20,000/mo",  location:"Bangalore",      workType:"Hybrid",         role:"Frontend Development", tags:["unacademy","edtech","frontend","web","react"] },
  { id:132, title:"Byju's ML Engineer Intern",             org:"Byju's",       domain:"EdTech / AI",           desc:"Build personalised learning recommendation engines using ML and deep learning.",   url:"https://byjus.com/careers",                                                             duration:"3 months",  stipend:"₹30,000/mo",  location:"Bangalore",      workType:"In Office",      role:"ML Engineering", tags:["byjus","edtech","ml","ai","recommendation"] },
  { id:133, title:"Postman Engineering Intern",             org:"Postman",      domain:"API Development",      desc:"Work on the world's most popular API development and testing platform.",             url:"https://www.postman.com/company/careers",                                               duration:"3 months",  stipend:"₹40,000/mo",  location:"Bangalore",      workType:"Hybrid",         role:"SDE", tags:["postman","api","testing","developer tools","sde"] },
  { id:134, title:"Freshworks Product Intern",             org:"Freshworks",   domain:"SaaS / Product",        desc:"Help shape SaaS products used by 50,000+ businesses globally.",                    url:"https://www.freshworks.com/company/careers",                                            duration:"3 months",  stipend:"₹30,000/mo",  location:"Chennai",        workType:"In Office",      role:"Product Management", tags:["freshworks","saas","product","pm","business"] },
  { id:135, title:"Notion Design Intern",                  org:"Notion",       domain:"Product Design",        desc:"Contribute to one of the world's most loved productivity tools' design system.",   url:"https://www.notion.so/careers",                                                         duration:"3 months",  stipend:"Paid",         location:"Remote",         workType:"Work from Home", role:"UI/UX Design", tags:["notion","design","ui","ux","productivity"] },
  { id:136, title:"CrowdStrike Cybersecurity Intern",      org:"CrowdStrike",  domain:"Cybersecurity",         desc:"Work on endpoint protection, threat intelligence and cloud security.",               url:"https://www.crowdstrike.com/careers/internships",                                       duration:"3 months",  stipend:"Paid",         location:"Pune",           workType:"Hybrid",         role:"Cybersecurity", tags:["crowdstrike","security","cyber","threat","cloud"] },
  { id:137, title:"Palo Alto Security Engineering Intern", org:"Palo Alto Networks",domain:"Cybersecurity",    desc:"Build next-gen firewall and cloud security products protecting global enterprises.", url:"https://www.paloaltonetworks.com/careers/internships",                                 duration:"3 months",  stipend:"Paid",         location:"Bangalore",      workType:"In Office",      role:"Security Engineering", tags:["paloalto","security","cyber","firewall","cloud"] },
  { id:138, title:"Ola Maps & Navigation Intern",          org:"Ola",          domain:"Geospatial Tech",       desc:"Build mapping and real-time navigation systems for India's ride-hailing platform.", url:"https://www.olacabs.com/careers",                                                      duration:"3 months",  stipend:"₹25,000/mo",  location:"Bangalore",      workType:"Hybrid",         role:"Geospatial Engineering", tags:["ola","maps","navigation","geospatial","mobile"] },
  { id:139, title:"IBM Extreme Blue Internship", org:"IBM", domain:"Cloud & AI", desc:"Premium summer internship focusing on business and technical innovation in Cloud and AI.", url:"https://www.ibm.com/careers/internships", duration:"12 weeks", stipend:"Paid", location:"Bangalore", workType:"Hybrid", role:"Software Developer", tags:["ibm","cloud","ai","summer"] },
  { id:140, title:"Intel Hardware Engineering Intern", org:"Intel", domain:"Electronics", desc:"Work on next-generation processors and hardware validation.", url:"https://jobs.intel.com/internships", duration:"6 months", stipend:"Paid", location:"Bangalore", workType:"In Office", role:"Hardware Engineer", tags:["intel","hardware","electronics","engineering"] },
  { id:141, title:"Cisco Software Engineer Intern", org:"Cisco", domain:"Networking", desc:"Develop networking solutions and software-defined infrastructure.", url:"https://jobs.cisco.com/jobs/SearchJobs/?listFilterMode=1&projectOffset=0&keyword=intern", duration:"6 months", stipend:"Paid", location:"Pune", workType:"Hybrid", role:"Software Engineer", tags:["cisco","networking","sde"] },
  { id:142, title:"Oracle Cloud Infrastructure Intern", org:"Oracle", domain:"Cloud Computing", desc:"Build scalable cloud infrastructure and core services for Oracle Cloud.", url:"https://www.oracle.com/careers/students/", duration:"3 months", stipend:"Paid", location:"Hyderabad", workType:"In Office", role:"Cloud Engineer", tags:["oracle","cloud","infrastructure"] },
  { id:143, title:"SAP Labs Developer Intern", org:"SAP", domain:"Enterprise Software", desc:"Contribute to enterprise software solutions and cloud-native development.", url:"https://jobs.sap.com/go/SAP-Students-and-Graduates/3494701/", duration:"6 months", stipend:"Paid", location:"Bangalore", workType:"Hybrid", role:"Developer", tags:["sap","enterprise","development"] },
  { id:144, title:"VMware R&D Virtualization Intern", org:"VMware", domain:"Cloud & Virtualization", desc:"Work on core virtualization technologies and cloud management products.", url:"https://careers.vmware.com/students", duration:"3 months", stipend:"Paid", location:"Remote", workType:"Work from Home", role:"R&D Engineer", tags:["vmware","cloud","virtualization"] },
  { id:145, title:"Intuit FinTech SDE Intern", org:"Intuit", domain:"FinTech", desc:"Develop financial software products for millions of consumers and small businesses.", url:"https://jobs.intuit.com/students", duration:"6 months", stipend:"Paid", location:"Bangalore", workType:"Hybrid", role:"Software Engineer", tags:["intuit","fintech","sde"] },
  { id:146, title:"Paytm Backend Developer Intern", org:"Paytm", domain:"FinTech", desc:"Build highly scalable payment gateways and financial services.", url:"https://careers.paytm.com/", duration:"3 months", stipend:"₹35,000/mo", location:"Noida", workType:"In Office", role:"Backend Developer", tags:["paytm","fintech","backend"] },
  { id:147, title:"MakeMyTrip Frontend Intern", org:"MakeMyTrip", domain:"Web Development", desc:"Create seamless travel booking experiences using React.js and Next.js.", url:"https://careers.makemytrip.com/", duration:"3 months", stipend:"₹30,000/mo", location:"Gurgaon", workType:"Hybrid", role:"Frontend Developer", tags:["makemytrip","frontend","web"] },
  { id:148, title:"Dream11 Data Engineering Intern", org:"Dream11", domain:"Data Science", desc:"Build resilient data pipelines for real-time sports fantasy analytics.", url:"https://about.dream11.in/careers", duration:"3 months", stipend:"₹40,000/mo", location:"Mumbai", workType:"In Office", role:"Data Engineer", tags:["dream11","data","engineering"] },
  { id:149, title:"Myntra App Development Intern", org:"Myntra", domain:"Mobile Development", desc:"Develop features for India's leading fashion e-commerce mobile app.", url:"https://careers.myntra.com/", duration:"6 months", stipend:"₹45,000/mo", location:"Bangalore", workType:"Hybrid", role:"Android Developer", tags:["myntra","app","mobile","android"] },
  { id:150, title:"Lenskart Computer Vision Intern", org:"Lenskart", domain:"AI/ML", desc:"Develop 3D try-on and facial analysis features using computer vision.", url:"https://hiring.lenskart.com/", duration:"3 months", stipend:"₹30,000/mo", location:"Gurgaon", workType:"In Office", role:"CV Engineer", tags:["lenskart","cv","ai","ml"] },
  { id:151, title:"Oyo Revenue Management Intern", org:"Oyo", domain:"Finance", desc:"Analyze pricing strategies and hotel revenue data to optimize yields.", url:"https://careers.oyorooms.com/", duration:"3 months", stipend:"₹20,000/mo", location:"Gurgaon", workType:"Hybrid", role:"Revenue Analyst", tags:["oyo","finance","data","analytics"] },
  { id:152, title:"Groww Product Management Intern", org:"Groww", domain:"Product Management", desc:"Assist in roadmap planning and feature delivery for investment products.", url:"https://groww.in/about-us", duration:"6 months", stipend:"₹35,000/mo", location:"Bangalore", workType:"In Office", role:"Product Manager", tags:["groww","pm","fintech"] },
  { id:153, title:"ShareChat Machine Learning Intern", org:"ShareChat", domain:"AI/ML", desc:"Build advanced recommendation systems for regional content feeds.", url:"https://sharechat.com/about/careers", duration:"6 months", stipend:"₹50,000/mo", location:"Bangalore", workType:"Hybrid", role:"ML Engineer", tags:["sharechat","ml","ai","recommendation"] },
  { id:154, title:"BharatPe Cybersecurity Intern", org:"BharatPe", domain:"Cybersecurity", desc:"Perform vulnerability assessments and strengthen payment infrastructure security.", url:"https://bharatpe.com/careers", duration:"3 months", stipend:"₹30,000/mo", location:"Delhi", workType:"In Office", role:"Cybersecurity Analyst", tags:["bharatpe","cybersecurity","security"] },
  { id:155, title:"Dunzo Operations Intern", org:"Dunzo", domain:"Logistics", desc:"Optimize delivery fleet operations and supply chain efficiency.", url:"https://www.dunzo.com/careers", duration:"3 months", stipend:"₹20,000/mo", location:"Bangalore", workType:"In Office", role:"Operations Analyst", tags:["dunzo","operations","logistics"] },
  { id:156, title:"Blinkit UI/UX Intern", org:"Blinkit", domain:"UI/UX Design", desc:"Design intuitive interfaces for 10-minute grocery delivery app.", url:"https://blinkit.com/careers", duration:"3 months", stipend:"₹25,000/mo", location:"Gurgaon", workType:"Hybrid", role:"UI/UX Designer", tags:["blinkit","ui","ux","design"] },
  { id:157, title:"Upgrad Marketing Intern", org:"Upgrad", domain:"Marketing", desc:"Execute digital marketing campaigns and analyze user acquisition metrics.", url:"https://www.upgrad.com/careers/", duration:"3 months", stipend:"₹20,000/mo", location:"Mumbai", workType:"Hybrid", role:"Marketing Intern", tags:["upgrad","marketing","digital"] },
  { id:158, title:"Clear Tax Tech Intern", org:"Clear", domain:"Web Development", desc:"Develop and maintain robust web platforms for tax filing services.", url:"https://cleartax.in/s/careers", duration:"6 months", stipend:"₹40,000/mo", location:"Bangalore", workType:"In Office", role:"Full Stack Developer", tags:["clear","web","frontend","backend"] },
  { id:159, title:"Urban Company DevOps Intern", org:"Urban Company", domain:"DevOps", desc:"Streamline CI/CD pipelines and monitor microservices deployment.", url:"https://careers.urbancompany.com/", duration:"6 months", stipend:"₹35,000/mo", location:"Gurgaon", workType:"In Office", role:"DevOps Engineer", tags:["urbancompany","devops","cloud"] },
  { id:160, title:"Pharmeasy Data Science Intern", org:"Pharmeasy", domain:"Data Science", desc:"Build predictive models for inventory management and demand forecasting.", url:"https://pharmeasy.in/careers", duration:"3 months", stipend:"₹30,000/mo", location:"Mumbai", workType:"Hybrid", role:"Data Scientist", tags:["pharmeasy","data","ml"] },
  { id:161, title:"Jio 5G Networks Intern", org:"Jio", domain:"Telecommunications", desc:"Research and develop network optimization tools for 5G infrastructure.", url:"https://careers.jio.com/", duration:"6 months", stipend:"₹25,000/mo", location:"Navi Mumbai", workType:"In Office", role:"Network Engineer", tags:["jio","telecom","5g","networking"] },
  { id:162, title:"Airtel Digital Marketing Intern", org:"Airtel", domain:"Marketing", desc:"Assist in executing telecom growth marketing strategies and user engagement.", url:"https://www.airtel.in/careers/", duration:"3 months", stipend:"₹15,000/mo", location:"Gurgaon", workType:"Hybrid", role:"Marketing Analyst", tags:["airtel","marketing","digital"] },
  { id:163, title:"HDFC Risk Analysis Intern", org:"HDFC Bank", domain:"Finance", desc:"Analyze credit risk and develop statistical models for financial products.", url:"https://www.hdfcbank.com/about-us/careers", duration:"2 months", stipend:"Paid", location:"Mumbai", workType:"In Office", role:"Risk Analyst", tags:["hdfc","finance","risk"] },
  { id:164, title:"KPMG Cyber Security Consulting Intern", org:"KPMG", domain:"Cybersecurity", desc:"Assist in auditing and consulting clients on cybersecurity best practices.", url:"https://kpmg.com/in/en/home/careers.html", duration:"3 months", stipend:"Paid", location:"Delhi", workType:"In Office", role:"Consultant", tags:["kpmg","cybersecurity","consulting"] },
  { id:165, title:"PwC Data Strategy Intern", org:"PwC", domain:"Data Science", desc:"Provide data-driven insights and strategy consulting to enterprise clients.", url:"https://www.pwc.in/careers.html", duration:"3 months", stipend:"Paid", location:"Bangalore", workType:"Hybrid", role:"Data Strategy Intern", tags:["pwc","data","strategy","consulting"] },
  { id:166, title:"EY Technology Risk Intern", org:"EY", domain:"Finance", desc:"Evaluate IT controls, assess risks and support audit engagements.", url:"https://www.ey.com/en_in/careers", duration:"2 months", stipend:"Paid", location:"Gurgaon", workType:"In Office", role:"Tech Risk Intern", tags:["ey","finance","audit","risk"] },
  { id:167, title:"Bain Associate Consultant Intern", org:"Bain & Company", domain:"Management Consulting", desc:"Work alongside consultants to solve complex business challenges.", url:"https://www.bain.com/careers/", duration:"10 weeks", stipend:"Paid (premium)", location:"Mumbai", workType:"In Office", role:"Associate Consultant", tags:["bain","consulting","strategy","management"] },
  { id:168, title:"BCG Product Management Intern", org:"BCG", domain:"Product Management", desc:"Drive digital product strategy and delivery across varying industries.", url:"https://careers.bcg.com/", duration:"10 weeks", stipend:"Paid (premium)", location:"Delhi", workType:"Hybrid", role:"Product Manager", tags:["bcg","pm","consulting","digital"] },
  { id:169, title:"Siemens Automation Engineering Intern", org:"Siemens", domain:"Engineering", desc:"Develop software solutions for industrial automation and smart infrastructure.", url:"https://jobs.siemens.com/jobs", duration:"6 months", stipend:"Paid", location:"Pune", workType:"In Office", role:"Automation Engineer", tags:["siemens","engineering","automation"] },
  { id:170, title:"Bosch IoT Intern", org:"Bosch", domain:"Internet of Things", desc:"Create connected solutions and edge computing applications for smart devices.", url:"https://careers.smartrecruiters.com/BoschGroup", duration:"6 months", stipend:"Paid", location:"Bangalore", workType:"Hybrid", role:"IoT Developer", tags:["bosch","iot","edge","hardware"] },
  { id:171, title:"GE Aviation Software Intern", org:"General Electric", domain:"Aviation/Tech", desc:"Develop critical software systems for aviation diagnostics and operations.", url:"https://jobs.gecareers.com/global/en", duration:"6 months", stipend:"Paid", location:"Bangalore", workType:"In Office", role:"Software Developer", tags:["ge","aviation","software"] },
  { id:172, title:"L&T Civil Engineering Intern", org:"L&T", domain:"Core Engineering", desc:"Gain hands-on experience in mega infrastructure and construction projects.", url:"https://www.larsentoubro.com/corporate/careers/", duration:"2 months", stipend:"₹10,000/mo", location:"Mumbai", workType:"In Office", role:"Civil Engineer", tags:["lnt","engineering","infrastructure","civil"] },
  { id:173, title:"Reliance Petrochemical Intern", org:"Reliance Industries", domain:"Chemical Engineering", desc:"Work on process optimization and plant operations in petrochemicals.", url:"https://careers.ril.com/", duration:"2 months", stipend:"₹15,000/mo", location:"Jamnagar", workType:"In Office", role:"Process Engineer", tags:["reliance","chemical","engineering"] },
  { id:174, title:"Mahindra Automotive Design Intern", org:"Mahindra", domain:"Core Engineering", desc:"Assist in vehicle design, testing and EV development initiatives.", url:"https://www.mahindra.com/careers", duration:"3 months", stipend:"₹15,000/mo", location:"Chennai", workType:"In Office", role:"Design Engineer", tags:["mahindra","automotive","design","ev"] },
  { id:175, title:"Tata Motors EV Tech Intern", org:"Tata Motors", domain:"Core Engineering", desc:"Research battery technologies and electric vehicle drivetrains.", url:"https://www.tatamotors.com/careers/", duration:"6 months", stipend:"₹20,000/mo", location:"Pune", workType:"In Office", role:"EV Engineer", tags:["tata","ev","automotive","engineering"] },
  { id:176, title:"Maruti Manufacturing Operations Intern", org:"Maruti Suzuki", domain:"Core Engineering", desc:"Implement lean manufacturing and production optimization techniques.", url:"https://www.marutisuzuki.com/corporate/careers", duration:"2 months", stipend:"₹10,000/mo", location:"Manesar", workType:"In Office", role:"Operations Engineer", tags:["maruti","manufacturing","operations"] },
  { id:177, title:"HUL Supply Chain Intern", org:"HUL", domain:"Supply Chain", desc:"Work on logistics, demand planning and FMCG supply chain efficiency.", url:"https://careers.unilever.com/india", duration:"2 months", stipend:"Paid (premium)", location:"Mumbai", workType:"Hybrid", role:"Supply Chain Intern", tags:["hul","fmcg","supply chain","logistics"] },
  { id:178, title:"ITC Brand Management Intern", org:"ITC", domain:"Marketing", desc:"Develop brand marketing campaigns and analyze consumer behavior.", url:"https://www.itcportal.com/careers/", duration:"2 months", stipend:"Paid", location:"Kolkata", workType:"In Office", role:"Brand Manager", tags:["itc","fmcg","marketing","brand"] },
  { id:179, title:"Nestle Food Tech Intern", org:"Nestle", domain:"Research & Development", desc:"Assist in product development, quality assurance and food technology research.", url:"https://www.nestle.in/jobs", duration:"6 months", stipend:"Paid", location:"Delhi", workType:"In Office", role:"Food Technologist", tags:["nestle","fmcg","rnd","food tech"] },
  { id:180, title:"P&G Consumer Research Intern", org:"P&G", domain:"Marketing", desc:"Conduct market research and implement data-driven marketing strategies.", url:"https://www.pgcareers.com/global/en/india-internships", duration:"2 months", stipend:"Paid", location:"Mumbai", workType:"Hybrid", role:"Consumer Researcher", tags:["png","fmcg","marketing","research"] },
  { id:181, title:"Cognizant Cloud Apps Intern", org:"Cognizant", domain:"Cloud Computing", desc:"Develop and deploy cloud-native applications on AWS and Azure.", url:"https://careers.cognizant.com/global/en", duration:"3 months", stipend:"₹20,000/mo", location:"Chennai", workType:"In Office", role:"Cloud App Developer", tags:["cognizant","cloud","apps","it"] },
  { id:182, title:"Wipro Cybersecurity Operations Intern", org:"Wipro", domain:"Cybersecurity", desc:"Monitor security events, perform triage and analyze threat intelligence.", url:"https://careers.wipro.com/careers-home/", duration:"6 months", stipend:"₹20,000/mo", location:"Bangalore", workType:"Hybrid", role:"Security Analyst", tags:["wipro","cybersecurity","security","it"] },
  { id:183, title:"HCL IoT & Embedded Sys Intern", org:"HCLTech", domain:"Internet of Things", desc:"Work on embedded systems programming and IoT device integration.", url:"https://www.hcltech.com/careers", duration:"6 months", stipend:"₹20,000/mo", location:"Noida", workType:"In Office", role:"Embedded Engineer", tags:["hcl","iot","embedded","it"] },
  { id:184, title:"Tech Mahindra AI/ML Intern", org:"Tech Mahindra", domain:"AI/ML", desc:"Develop enterprise AI solutions utilizing computer vision and NLP models.", url:"https://careers.techmahindra.com/", duration:"3 months", stipend:"₹15,000/mo", location:"Pune", workType:"In Office", role:"ML Engineer", tags:["techmahindra","ai","ml","it"] },
  { id:185, title:"Capgemini Data Analytics Intern", org:"Capgemini", domain:"Data Science", desc:"Perform data wrangling and build dashboards for business intelligence.", url:"https://www.capgemini.com/in-en/careers/", duration:"3 months", stipend:"₹20,000/mo", location:"Mumbai", workType:"Hybrid", role:"Data Analyst", tags:["capgemini","data","analytics","it"] },
  { id:186, title:"Accenture Strategy Tech Intern", org:"Accenture", domain:"Management Consulting", desc:"Contribute to enterprise architecture planning and IT strategy.", url:"https://www.accenture.com/in-en/careers", duration:"3 months", stipend:"Paid", location:"Bangalore", workType:"In Office", role:"Strategy Consultant", tags:["accenture","strategy","tech","consulting"] },
  { id:187, title:"CGI Full Stack Intern", org:"CGI", domain:"Web Development", desc:"Develop responsive web platforms using Java, Spring Boot, and Angular.", url:"https://www.cgi.com/india/en/careers", duration:"6 months", stipend:"₹25,000/mo", location:"Bangalore", workType:"In Office", role:"Full Stack Developer", tags:["cgi","fullstack","java","angular"] },
  { id:188, title:"Mindtree Cloud Migration Intern", org:"Mindtree", domain:"Cloud Computing", desc:"Assist in migrating legacy on-premise applications to modern cloud architecture.", url:"https://www.ltimindtree.com/careers/", duration:"3 months", stipend:"₹20,000/mo", location:"Bangalore", workType:"Hybrid", role:"Cloud Engineer", tags:["mindtree","ltimindtree","cloud","migration"] },
  { id:189, title:"Hexaware Automation Testing Intern", org:"Hexaware", domain:"Quality Assurance", desc:"Design test cases and build automation scripts using Selenium.", url:"https://hexaware.com/careers/", duration:"6 months", stipend:"₹15,000/mo", location:"Chennai", workType:"In Office", role:"QA Engineer", tags:["hexaware","testing","qa","automation"] },
  { id:190, title:"Zensar UI/UX Research Intern", org:"Zensar", domain:"UI/UX Design", desc:"Conduct user research and create wireframes for enterprise software interfaces.", url:"https://www.zensar.com/careers", duration:"3 months", stipend:"₹15,000/mo", location:"Pune", workType:"Hybrid", role:"UX Researcher", tags:["zensar","ui","ux","research","design"] },
];

/**
 * Seed all curated entries into OpportunityCatalog.
 * Uses updateOne+upsert so running multiple times is safe (idempotent).
 */
async function seedCatalog() {
  let inserted = 0;
  let skipped  = 0;

  const all = [
    ...COMPETITIONS.map(c => ({ ...c, type: 'competition' })),
    ...INTERNSHIPS .map(i => ({ ...i, type: 'internship'  })),
  ];

  for (const item of all) {
    const filter = { title: item.title, type: item.type };
    const doc = {
      type:        item.type,
      title:       item.title,
      org:         item.org        || '',
      domain:      item.domain     || '',
      description: item.desc       || '',
      url:         item.url        || '',
      category:    item.category   || '',
      tags:        item.tags       || [],
      status:      item.status     || 'Live',
      eventType:   item.eventType  || '',
      payment:     item.payment    || '',
      teamSize:    item.teamSize   || '',
      location:    item.location   || '',
      workType:    item.workType   || '',
      duration:    item.duration   || '',
      stipend:     item.stipend    || '',
      role:        item.role       || '',
      source:      'curated',
      datePosted:  item.datePosted || '',
    };

    const result = await OpportunityCatalog.updateOne(filter, { $setOnInsert: doc }, { upsert: true });
    if (result.upsertedCount > 0) inserted++;
    else skipped++;
  }

  console.log(`[Catalog] ✅ Seed complete — ${inserted} inserted, ${skipped} already existed`);
}

module.exports = { seedCatalog };
